version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      all-dependencies:
        update-types:
          - major
          - minor
          - patch
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - skip-changelog

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      all-actions:
        update-types:
          - major
          - minor
          - patch
    labels:
      - dependencies
      - github-actions
      - skip-changelog
